import vue from 'vue'
import { Input, Form, FormItem, Card, Button, Menu, MenuItem, Submenu, Header, Container,
    Aside, DropdownItem, DropdownMenu, Main, Dropdown, Table, TableColumn, Radio, Checkbox, Select,
    CheckboxGroup, RadioGroup, Option, Col, Row
} from 'element-ui'

// vue.use(Element)
vue.use(Input)
    .use(Form)
    .use(FormItem)
    .use(Card)
    .use(Button)
    .use(Menu)
    .use(Aside)
    .use(Header)
    .use(Container)
    .use(MenuItem)
    .use(Submenu)
    .use(DropdownItem)
    .use(DropdownMenu)
    .use(Main)
    .use(Dropdown)
    .use(Table)
    .use(TableColumn)
    .use(Radio)
    .use(Checkbox)
    .use(Select)
    .use(CheckboxGroup)
    .use(Option)
    .use(Col)
    .use(Row)
    .use(RadioGroup)
// vue.component(Table.name, Table)
// vue.component(Input.name, Input)
// vue.component(Input.name, Input)
// vue.component(Input.name, Input)
// vue.component(Input.name, Input)
// vue.component(Input.name, Input)
// vue.component(FormItem.name, FormItem)
// vue.component(Card.name, Card)
// vue.component(Button.name, Button)
// vue.component(Form.name, Form)

